export const SITE_CONFIG = {
  name: 'Gulf Blvd Concrete Works',
  shortName: 'Concrete Gulf Blvd',
  phone: '(727) 346-8556',
  email: 'info@gulfblvdconcrete.com',
  address: 'Indian Rocks Beach, FL 33785',
  domain: 'https://gulfblvdconcrete.com',
  description: 'Concrete driveways, pool decks, patios, and foundations along Gulf Blvd — Indian Rocks Beach to Clearwater Beach. Marine-grade materials rated for salt air. Licensed & insured. Free estimates.',
  services: [
    { title: 'Concrete Driveways', href: '/services/concrete-driveways', description: 'Durable concrete driveways for Gulf Blvd homes — designed for Florida heat, humidity, and salt-air exposure.' },
    { title: 'Pool Deck Resurfacing', href: '/services/pool-deck-resurfacing', description: 'Pool deck installation, resurfacing, and repair. Slip-resistant, UV-stable finishes rated for Florida pool environments.' },
    { title: 'Concrete Patios & Outdoor Living', href: '/services/concrete-patios', description: 'Custom concrete patios for Gulf Coast outdoor living — stamped, colored, or brushed finish available.' },
    { title: 'Walkways & Sidewalks', href: '/services/concrete-walkways-sidewalks', description: 'Concrete walkways and sidewalks — clean, durable, and safe for coastal Florida properties.' },
    { title: 'Concrete Repair & Restoration', href: '/services/concrete-repair', description: 'Crack repair, spalling restoration, and joint sealing for deteriorating concrete surfaces.' },
    { title: 'Decorative & Stamped Concrete', href: '/services/decorative-concrete', description: 'Stamped, colored, and decorative concrete for driveways, patios, and pool decks.' },
    { title: 'Marine-Grade Concrete Sealing', href: '/services/marine-grade-concrete-sealing', description: 'Professional sealing with marine-grade products rated for salt air and coastal UV exposure.' },
    { title: 'Concrete Walls & Retaining', href: '/services/concrete-walls', description: 'Concrete retaining walls, garden walls, and privacy walls — engineered for Florida soil conditions.' },
    { title: 'Hurricane-Ready Concrete Foundations', href: '/services/concrete-foundations', description: 'Concrete foundations poured to Florida Building Code standards — engineered for hurricane-zone requirements.' },
    { title: 'Concrete Slabs', href: '/services/concrete-slabs', description: 'Patio slabs, shed bases, and utility pads — properly reinforced for Florida clay and sandy soil conditions.' },
    { title: 'Slab Leveling & Lifting', href: '/services/mudjacking-slab-leveling', description: 'Restore sunken or uneven slabs without full replacement. Cost-effective lifting for driveways, patios, and pool decks.' },
    { title: 'Concrete Overlay & Resurfacing', href: '/services/concrete-overlay', description: 'Transform old, stained, or cracked concrete with a fresh overlay — a fraction of the cost of replacement.' },
  ],
  locations: [
    { city: 'Indian Rocks Beach', href: '/cities/indian-rocks-beach' },
    { city: 'Indian Shores', href: '/cities/indian-shores' },
    { city: 'Redington Shores', href: '/cities/redington-shores' },
    { city: 'Redington Beach', href: '/cities/redington-beach' },
    { city: 'Madeira Beach', href: '/cities/madeira-beach' },
    { city: 'Treasure Island', href: '/cities/treasure-island' },
    { city: 'St. Pete Beach', href: '/cities/st-pete-beach' },
    { city: 'Clearwater Beach', href: '/cities/clearwater-beach' },
  ],
};
